CREATE TYPE "role" AS ENUM (
  'admin',
  'author',
  'reader'
);

CREATE TYPE "author_status" AS ENUM (
  'active',
  'inactive',
  'banned'
);

CREATE TYPE "post_status" AS ENUM (
  'draft',
  'published',
  'archived'
);

CREATE TABLE "users" (
  "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(255) UNIQUE NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "role" role DEFAULT 'reader',
  "created_at" timestamp DEFAULT (NOW())
);

CREATE TABLE "authors" (
  "author_id" bigint PRIMARY KEY,
  "first_name" varchar(255) NOT NULL,
  "last_name" varchar(255),
  "bio" text,
  "profile_picture_url" text,
  "author_status" author_status DEFAULT 'active',
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "blog_posts" (
  "blog_post_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "author_id" bigint NOT NULL,
  "title" varchar(255) NOT NULL,
  "content" text NOT NULL,
  "post_status" post_status DEFAULT 'draft',
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "published_at" timestamp,
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "categories" (
  "cat_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_name" varchar UNIQUE NOT NULL,
  "description" text
);

CREATE TABLE "post_categories" (
  "blog_post_id" bigint,
  "cat_id" bigint,
  PRIMARY KEY ("blog_post_id", "cat_id")
);

CREATE TABLE "commnets" (
  "comment_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" text NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTMP),
  "blog_post_id" bigint NOT NULL,
  "user_id" bigint NOT NULL
);

CREATE TABLE "post_view_count" (
  "blog_post_id" bigint PRIMARY KEY,
  "view_count" bigint DEFAULT 0
);

CREATE TABLE "post_view_logs" (
  "view_log_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "blog_post_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "viewed_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE INDEX ON "blog_posts" ("author_id");

CREATE INDEX ON "blog_posts" ("post_status");

CREATE INDEX ON "commnets" ("blog_post_id");

CREATE INDEX ON "commnets" ("user_id");

CREATE INDEX ON "post_view_logs" ("blog_post_id");

CREATE INDEX ON "post_view_logs" ("user_id");

ALTER TABLE "authors" ADD FOREIGN KEY ("author_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "blog_posts" ADD FOREIGN KEY ("author_id") REFERENCES "authors" ("author_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "post_categories" ADD FOREIGN KEY ("blog_post_id") REFERENCES "blog_posts" ("blog_post_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "post_categories" ADD FOREIGN KEY ("cat_id") REFERENCES "categories" ("cat_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "commnets" ADD FOREIGN KEY ("blog_post_id") REFERENCES "blog_posts" ("blog_post_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "commnets" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "post_view_count" ADD FOREIGN KEY ("blog_post_id") REFERENCES "blog_posts" ("blog_post_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "post_view_logs" ADD FOREIGN KEY ("blog_post_id") REFERENCES "blog_posts" ("blog_post_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "post_view_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;
